# Oh my zsh
export ZSH=/Users/alvaro/.oh-my-zsh
ZSH_THEME="cbira"
plugins=(
  git
  go
  colored-man-pages
)
source $ZSH/oh-my-zsh.sh

# Sensible defaults
setopt appendhistory autocd extendedglob nomatch
# bindkey -v
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward
zstyle :compinstall filename '/home/alvaro/.zshrc'
autoload -Uz compinit
compinit
export PROMPT_EOL_MARK=''
export HISTFILE=~/.histfile
export HISTSIZE=10000
export SAVEHIST=10000
export DISABLE_AUTO_TITLE="true"
export EDITOR="vim"
export PATH="$PATH:/Users/alvaro/dotfiles/scripts"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
export HOMEBREW_NO_AUTO_UPDATE=true

# Go
export GOPATH=~/Developer/go
export PATH=$PATH:$GOPATH/bin

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home
    
# Base 16, used for FZF and bat
BASE16_SHELL="$HOME/.config/base16-shell/"
export BASE16_THEME="gruvbox-dark-medium"

source /usr/local/etc/profile.d/z.sh
source ~/dotfiles/zsh/fzf.zsh
source ~/dotfiles/zsh/zsh_aliases
#
