export ZSH=/Users/alvaro/.oh-my-zsh
ZSH_THEME="cbira"
plugins=(
  git
  colored-man-pages
  fzf-tab
  zsh-completions
  golang
  pip
  osx
  gradle
)
source $ZSH/oh-my-zsh.sh

setopt appendhistory autocd extendedglob nomatch
zstyle :compinstall filename '/home/alvaro/.zshrc'
autoload -Uz compinit
compinit

bindkey "^P" history-beginning-search-backward; 
bindkey "^N" history-beginning-search-forward
bindkey "^K" up-line-or-beginning-search #history-beginning-search-backward
bindkey "^J" down-line-or-beginning-search #history-beginning-search-forward

export PROMPT_EOL_MARK=''
export HISTFILE=~/.histfile
export HISTSIZE=1000000
export SAVEHIST=1000000
export DISABLE_AUTO_TITLE="true"
export EDITOR="nvim"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
export HOMEBREW_NO_AUTO_UPDATE=true

export GF_BAT_STYLE=changes
export GF_BAT_THEME=gruvbox
export BAT_THEME=gruvbox

export DOTFILES=/Users/alvaro/dotfiles
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:$DOTFILES/bin/git-fuzzy/bin"

export GOPATH=~/Developer/go
export PATH=$PATH:$GOPATH/bin

export SDKMAN_DIR="/Users/alvaro/.sdkman"
source "/Users/alvaro/.sdkman/bin/sdkman-init.sh"
eval "$(pyenv init - --no-rehash)"
# eval "$(swiftenv init -)"

source /usr/local/etc/profile.d/z.sh
source ~/dotfiles/zsh/fzf.zsh
source ~/dotfiles/zsh/aliases.zsh
source ~/dotfiles/zsh/work.zsh

# eval "$(gh completion -s zsh)"
# eval "$(kubectl completion zsh)"

# function get_cluster_short() {
#   echo "$1" | cut -d / -f2
# }

# KUBE_PS1_CLUSTER_FUNCTION=get_cluster_short
# KUBE_PS1_NS_ENABLE=false
# KUBE_PS1_SYMBOL_ENABLE=false
# source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
#

export DE_AWS_AUTH_ENABLED=true
