# Oh my zsh
export ZSH=/Users/alvaro/.oh-my-zsh
ZSH_THEME="cbira"
plugins=(
  git
  golang
  colored-man-pages
  fzf-tab
)
source $ZSH/oh-my-zsh.sh

# Sensible defaults
setopt appendhistory autocd extendedglob nomatch
bindkey "^P" history-beginning-search-backward; 
bindkey "^N" history-beginning-search-forward
bindkey "^K" up-line-or-beginning-search #history-beginning-search-backward
bindkey "^J" down-line-or-beginning-search #history-beginning-search-forward
zstyle :compinstall filename '/home/alvaro/.zshrc'
autoload -Uz compinit
compinit
export PROMPT_EOL_MARK=''
export HISTFILE=~/.histfile
export HISTSIZE=100000
export SAVEHIST=100000
export DISABLE_AUTO_TITLE="true"
export EDITOR="nvim"
export PATH="$PATH:/Users/alvaro/dotfiles/bin"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
export HOMEBREW_NO_AUTO_UPDATE=true

export GOPATH=~/Developer/go
export PATH=$PATH:$GOPATH/bin

export SDKMAN_DIR="/Users/alvaro/.sdkman"
[[ -s "/Users/alvaro/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/alvaro/.sdkman/bin/sdkman-init.sh"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi


source ~/.fzf.zsh
source /usr/local/etc/profile.d/z.sh
source ~/dotfiles/zsh/fzf.zsh
source ~/dotfiles/zsh/zsh_aliases
# source ~/dotfiles/bin/aws-helpers.sh
source ~/dotfiles/zsh/work.zsh

